#!/usr/bin/perl
#
# Programmer:    Craig Stuart Sapp <craig.stanford.edu>
# Creation Date: Wed Sep 16 22:39:51 PDT 2015
# Last Modified: Wed Sep 16 22:39:51 PDT 2015
# Filename:      drm:gh-pages/source/getsource
# Syntax:        perl 5
# vim:           ts=3
#
# Description:
#

use strict;

my $page = $ARGV[0];
if ($page =~ /^\s*$/) {
	$page = "Digital_Resources_for_Musicology";
}

my $base = "http://wiki.ccarh.org/index.php?title=";
my $basepage = "$base$page&action=edit";

my $content = getRawWikiFile($basepage);

open (MAIN, ">main.wiki") or die;
print MAIN $content;
close MAIN;

#print $content;
my @templates = getTemplates($content);
#print join("\n", @templates), "\n";

for (my $i=0; $i<@templates; $i++) {
   $content = getRawWikiFile("${base}Template:$templates[$i]&action=edit");
	open(FILE, ">$templates[$i].template");
	print FILE $content;
   close FILE;
}

exit(0);


##############################
##
## getRawWikiFile --
##

sub getRawWikiFile {
	my ($page) = @_;
	print "Downloading $page\n";
	my $content = `wget "$page" -O - 2> /dev/null`;
	$content =~ s/.*<textarea[^>]*>//is;
	$content =~ s/<\/textarea>.*//is;
	return $content;
}



##############################
##
## getTemplates --
##

sub getTemplates {
	my ($data) = @_;
	my @contents = split(/\n/, $data);
	my @output;
	for (my $i=0; $i<@contents; $i++) {
		next if $contents[$i] !~ /{{(.*)}}/;
		$output[@output] =  $1;
	}
	return @output;
}



